#!/usr/bin/env python3
"""build_sri.py -- the Simone Research Inventory (SRI) layer, GENERATED from canonical sources.

Jon 2026-09-05: "create a state of the art inventory that is easy to read and context friendly
for harnesses ... it is done when an agent can easily enter and know exactly what we have tried,
why we have tried it, what the methodology was, what the results were, and what we can learn
from it." Method: ~/.claude/skills/inventory (SRI) on top of the curate census
(workflow/curation/*). ASTRA 2026-09-05 rules honoured: one canonical source per fact, every
register row carries provenance (path#line + git blob) and a verification date, evidence is
kept separate from interpretation, nothing is deleted, no second database.

WHAT IS HAND-WRITTEN: exactly one file, workflow/inventories/sri/CURATED.json (project summary,
the five things, the A-list with why/next_action, the D do-not-resume list, the METHODS rows).
Every other file under workflow/inventories/sri/ is regenerated by this script from:

  workflow/DEAD-ENDS.md                       closed lines + scope guards + reopen conditions
  workflow/ATTEMPTS-LEDGER.md                 every table (GR rows, retracted kills, instruments
                                              that lied, P-series, ...) + the numbered §3d list
  workflow/inventories/TRIED-RESULTS-COMPACT.json, HYPOTHESIS-KILL-CARDS.json,
  workflow/canon/GRAVEYARD-INDEX.json         tried -> result cards, kill cards, burials
  workflow/NUMBERS-INVENTORY.md, workflow/inventories/METRICS-INVENTORY.json,
  workflow/canon/EQUATIONS.md, workflow/canon/RETRACTIONS.md          -> CLAIMS
  workflow/DECISIONS.md                       -> DECISIONS (one line per ruling)
  workflow/IMPROVEMENT-INVENTORY.md           -> OPEN (scarcity-closed rows carry a reopen trigger)
  workflow/canon/SUPERSESSION-REGISTER.md + D:/ptcg_archive manifests      -> TOMBSTONES
  workflow/ARTIFACT-CATALOG.jsonl + workflow/curation/labels.csv           -> MANIFEST.jsonl, TOOLS
  workflow/inventories/TOOLS-OUTPUT-EXISTS.json                            -> TOOLS output status

    python scripts/build_sri.py            # regenerate workflow/inventories/sri/
    python scripts/build_sri.py --check    # exit 1 if the committed layer differs from a rebuild

Verification vocabulary (CLAIMS): VERIFIED-AT-ARTIFACT (the value's numeric tokens were found in
the named source artifact on disk today) · RECEIPT-WEAK (source named but the tokens were not
found in it) · UNVERIFIABLE-HERE (producer is off-repo, e.g. D:\\) · RETRACTED (register). A
status is a statement about where the number can be read, never about whether it is true.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import date, datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
import retraction_register as rr  # noqa: E402

OUT = REPO / "workflow" / "inventories" / "sri"
REG = OUT / "registers"
CURATED = OUT / "CURATED.json"
CATALOG = REPO / "workflow" / "ARTIFACT-CATALOG.jsonl"
LABELS = REPO / "workflow" / "curation" / "labels.csv"
SCORECARD = REPO / "workflow" / "curation" / "SCORECARD.md"
ARCHIVE_ROOT = Path("D:/ptcg_archive")

SRC = {
    "dead_ends": "workflow/DEAD-ENDS.md",
    "ledger": "workflow/ATTEMPTS-LEDGER.md",
    "tried": "workflow/inventories/TRIED-RESULTS-COMPACT.json",
    "kill_cards": "workflow/inventories/HYPOTHESIS-KILL-CARDS.json",
    "graveyard": "workflow/canon/GRAVEYARD-INDEX.json",
    "numbers": "workflow/NUMBERS-INVENTORY.md",
    "metrics": "workflow/inventories/METRICS-INVENTORY.json",
    "equations": "workflow/canon/EQUATIONS.md",
    "retractions": "workflow/canon/RETRACTIONS.md",
    "decisions": "workflow/DECISIONS.md",
    "improvement": "workflow/IMPROVEMENT-INVENTORY.md",
    "supersession": "workflow/canon/SUPERSESSION-REGISTER.md",
    "tools_output": "workflow/inventories/TOOLS-OUTPUT-EXISTS.json",
    "learnings_index": "workflow/LEARNINGS.md",
    # ASTRA 2026-09-06 02:51Z located this family missing from both readers: 23 plain-language
    # lessons with root cause, the mechanism each became (M-rules), and receipts.
    "lessons": "workflow/LESSONS.md",
}

# Coverage ratchet (Jon 2026-09-05: "everything that we have done needs to be in that inventory").
# MASTER-INVENTORY-INDEX.json catalogues every inventory surface. On 2026-09-06 the harvest read 13 of
# its 57 surfaces; the 22 markdown surfaces below were catalogued but never harvested, so their tables
# and headings were invisible to `dock ask`. Each becomes LEARNINGS rows of kind `surface:<id>` — every
# table row and, for prose-only files, every heading with its first paragraph — with the same
# provenance rule. test_build_sri fails if a catalogued markdown surface is neither in SRC nor here.
MASTER_INDEX = "workflow/inventories/MASTER-INVENTORY-INDEX.json"
SURFACES = {
    "owned-revisit": "workflow/research/2026-08-11-OWNED-POLICY-REVISIT-INVENTORY.md",
    "own-policy": "workflow/research/2026-08-11-OWN-POLICY-INVENTORY.md",
    "graveyard-reconstruction": "workflow/research/2026-08-11-STRATEGY-GRAVEYARD-RECONSTRUCTION.md",
    "exploration-depth": "workflow/research/2026-08-11-STRATEGY-EXPLORATION-INVENTORY.md",
    "replay-stores": "workflow/REPLAY-STORES.md",
    "peer-mine": "workflow/PEER-MINE-15-BACKLOG.md",
    "missed-assets": "workflow/research/2026-08-10-missed-asset-inventory.md",
    "opportunity-catalog": "workflow/research/2026-08-11-INVENTORY-OPPORTUNITY-CATALOG.md",
    "doc-roles": "workflow/canon/DOC-ROLES.md",
    "reconciliation-0823": "workflow/research/2026-08-23-answers-exist-inventory-reconciliation.md",
    "full-history-audit-0824": "workflow/research/2026-08-24-full-history-inventory-audit.md",
    "loss-modes": "workflow/LOSS-MODES.md",
    "knowledge": "workflow/KNOWLEDGE.md",
    "asset-index": "workflow/ASSET-INDEX.md",
    "archive-policy": "workflow/canon/ARCHIVE-POLICY.md",
    "competitive-loop": "workflow/canon/COMPETITIVE-LOOP-OF-RECORD.md",
    "measured-0806": "workflow/canon/MEASURED-2026-08-06.md",
    "mu-strategy": "workflow/canon/MU-STRATEGY.md",
    "strategy-atlas": "workflow/canon/STRATEGY-ATLAS.md",
    "research-index": "workflow/research/INDEX.md",
    "measurements-index": "workflow/measurements/INDEX.md",
    "product-passport": "workflow/inventories/PRODUCT-PASSPORT.md",
}
# Catalogued surfaces that are routing pages or the SRI's own outputs, not knowledge sources.
NOT_A_SOURCE = ("workflow/NOW.md", "START-HERE.md", "AGENTS.md")

# Generated-metadata POSITIONS, not a global pattern. ASTRA 2026-09-06 11:15Z reproduced the defect
# in the first version, which ran one regex over the whole file: an ordinary sentence differing only
# in a date ("The run completed on 2026-09-04" vs "…-09-05") or in a main reference ("verified at
# main abcdef1234" vs "…deadbeef99") normalised EQUAL and was reported stamp-only, so real content
# drift exited 0. A line qualifies as stamp-only only if it IS one of the three generated metadata
# lines and differs ONLY in its date/commit field; every other differing line is content drift.
# The banner is line 0 of every generated markdown file; "Last inventory" is line 4 of INDEX.md
# only. Each pattern captures its permitted VALUES as groups, and everything outside those groups
# must match exactly — so a change anywhere else on the line, of any shape, is content drift.
BANNER_LINE = re.compile(r"^(<!-- GENERATED by scripts/build_sri\.py\s.*?on )(\d{4}-\d{2}-\d{2})( at main )([0-9a-f]{6,40})(.*-->)$")
LAST_INVENTORY_LINE = re.compile(r"^(\*\*Last inventory:\*\* )(\d{4}-\d{2}-\d{2})(.*)$")
PERMITTED_VALUE_GROUPS = {BANNER_LINE: (2, 4), LAST_INVENTORY_LINE: (2,)}


def _outside_permitted_values(pat: "re.Pattern[str]", line: str) -> tuple | None:
    """The line's fixed parts, with only the permitted value groups removed. None if it is not this
    metadata line at all."""
    m = pat.match(line)
    if not m:
        return None
    allowed = PERMITTED_VALUE_GROUPS[pat]
    return tuple(g for i, g in enumerate(m.groups(), 1) if i not in allowed)


def stamp_only_difference(rel: str, on_disk: str, fresh: str) -> bool:
    """True when two versions of a generated file differ ONLY in generated build metadata.

    ASTRA 2026-09-06 11:15Z and 11:33Z, both reproduced by extracting the patterns through AST:
      - a global regex forgave ordinary prose differing only in a date or a main reference;
      - then a per-line rule still forgave a JSON-shaped `"main": "…"` line appearing inside a
        MARKDOWN register, and forgave a changed hex-like token elsewhere on the "Last inventory"
        line, because the normaliser blanked every date/hex on a line it had decided to trust.

    So: the metadata POSITION is fixed (banner = line 0; "Last inventory" = INDEX.md only), the
    permitted VALUES are captured groups, and everything outside those groups must match exactly.
    BUILD.json needs no rule at all — `--check` never compares it. Any other difference, on any
    line, of any shape, is content drift."""
    a, b = on_disk.splitlines(), fresh.splitlines()
    if len(a) != len(b):
        return False
    for i, (la, lb) in enumerate(zip(a, b)):
        if la == lb:
            continue
        if i == 0 and rel.endswith(".md"):
            fa, fb = _outside_permitted_values(BANNER_LINE, la), _outside_permitted_values(BANNER_LINE, lb)
            if fa is not None and fa == fb:
                continue
        # ASTRA 2026-09-06 11:41Z, third boundary: the INDEX-only guard still allowed a line of this
        # SHAPE anywhere in the file, so body prose beginning "**Last inventory:** <date>" would have
        # had its date forgiven. render_index emits the real header at index 3; pin it there.
        if rel == "INDEX.md" and i == 3:
            fa, fb = _outside_permitted_values(LAST_INVENTORY_LINE, la), _outside_permitted_values(LAST_INVENTORY_LINE, lb)
            if fa is not None and fa == fb:
                continue
        return False
    return True

NUM_TOKEN = re.compile(r"(?<![\w.])[+\-−]?\d[\d,]*(?:\.\d+)?(?![\w.])")
BACKTICK_PATH = re.compile(r"`([^`]+)`")


# ---------------------------------------------------------------- git + io helpers
def sh(args: list[str]) -> str:
    r = subprocess.run(args, cwd=str(REPO), capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=300)
    return r.stdout if r.returncode == 0 else ""


def blob_map() -> dict[str, str]:
    out: dict[str, str] = {}
    for entry in sh(["git", "ls-files", "-s", "-z"]).split("\0"):
        if not entry.strip():
            continue
        meta, _, path = entry.partition("\t")
        parts = meta.split()
        if len(parts) >= 2 and path:
            out[path] = parts[1]
    return out


def read(rel: str) -> str:
    p = REPO / rel
    return p.read_text(encoding="utf-8", errors="replace") if p.exists() else ""


def cells(line: str) -> list[str]:
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    return [c.strip() for c in body.split("|")]


def is_sep(cs: list[str]) -> bool:
    return bool(cs) and all(re.fullmatch(r":?-{2,}:?", c) for c in cs if c) and any(cs)


def tables(text: str) -> list[dict]:
    """Every markdown table: {'section', 'header', 'rows': [(line_no, cells)]}."""
    out: list[dict] = []
    section = ""
    cur: dict | None = None
    for i, line in enumerate(text.splitlines(), 1):
        if line.startswith("#"):
            section = line.lstrip("# ").strip()
            cur = None
            continue
        if line.lstrip().startswith("|"):
            cs = cells(line)
            if cur is None:
                cur = {"section": section, "header": cs, "rows": [], "line": i}
                out.append(cur)
                continue
            if is_sep(cs):
                continue
            cur["rows"].append((i, cs))
        else:
            cur = None
    return [t for t in out if t["rows"]]


def clean(s: str, n: int = 220) -> str:
    s = re.sub(r"\s+", " ", s.replace("|", "/")).strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def src_ref(rel: str, line: int | None, blobs: dict[str, str]) -> str:
    """`path` L<line> (blob …) — the path stays alone inside the backticks so validate.py's
    G6 gate can resolve it on disk; the line and the blob ride outside."""
    b = blobs.get(rel, "")
    return f"`{rel}`" + (f" L{line}" if line else "") + (f" (blob {b[:10]})" if b else " (UNTRACKED)")


# ---------------------------------------------------------------- typed retrieval tags
# Jon 2026-09-06 ("organize the inventory further so it is very easy for harnesses to search"):
# a small controlled vocabulary derived from each row's own words. Tags are RETRIEVAL KEYS, never
# verdicts — the same rule as prior_art's keyword hints. A row can carry several.
TAG_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("family:search", ("search", "pimc", "mcts", "rollout", "belief", "determiniz", "puct", "leaf")),
    ("family:deck", ("deck", "archetype", "crustle", "grimmsnarl", "dragapult", "garchomp", "lucario", "alakazam", "mill", "energy")),
    ("family:rules", ("rule", "heuristic", "patch", "lever", "priority", "scorer", "ko ", "knockout", "gust", "bench")),
    ("family:learning", ("imitation", "bc ", "behavior-clon", "label", "train", "net", "value_net", "rlvr", "dagger", "auc", "represent")),
    ("family:teacher", ("teacher", "coach", "oracle", "council", "student", "distill", "intervention")),
    ("instrument:panel", ("panel", "opponent", "band pool", "lineage", "self-similar")),
    ("instrument:ship-path", ("ship", "tar", "bundle", "submitted", "fielded", "flag", "knob", "main.py")),
    ("instrument:power", ("underpower", "mde", "n=400", "n>=1200", "n≥1200", "sigma", "power", "noise")),
    ("instrument:ladder", ("ladder", "mu", "μ", "leaderboard", "submission", "trueskill", "elo")),
    ("instrument:identity", ("identity", "sha", "hash", "blob", "byte", "provenance", "custody")),
    ("process:review", ("verif", "certif", "review", "author", "sabotage", "attestation")),
    ("process:comms", ("bus", "mailbox", "watcher", "liveness", "heartbeat", "roster")),
    ("process:memory", ("inventory", "register", "rediscover", "bank", "index", "catalog", "retract")),
]


def tags_for(text: str) -> list[str]:
    low = text.lower()
    return [tag for tag, keys in TAG_RULES if any(k in low for k in keys)]


# ---------------------------------------------------------------- harvest: LEARNINGS
def harvest_learnings(blobs: dict[str, str]) -> list[dict]:
    rows: list[dict] = []
    # DEAD-ENDS: every table; the A-table has the scope guard + reopen columns.
    de = read(SRC["dead_ends"])
    for t in tables(de):
        h = [x.lower() for x in t["header"]]
        for ln, cs in t["rows"]:
            if len(cs) < 3:
                continue
            row = {"kind": "dead-end", "section": t["section"], "id": clean(cs[0].strip("*` "), 24),
                   "tried": clean(cs[1], 160), "happened": clean(cs[2], 260), "scope_guard": "", "reopen": "",
                   "source": src_ref(SRC["dead_ends"], ln, blobs)}
            if any("scope" in x for x in h) and len(cs) >= 4:
                row["scope_guard"] = clean(cs[3], 260)
            if any("re-open" in x or "reopen" in x for x in h) and len(cs) >= 5:
                row["reopen"] = clean(cs[4], 200)
            rows.append(row)
    # ATTEMPTS-LEDGER: every table becomes rows (GR rows, retracted kills, P-series, ...).
    led = read(SRC["ledger"])
    for t in tables(led):
        for ln, cs in t["rows"]:
            if len(cs) < 2:
                continue
            rows.append({"kind": "ledger", "section": t["section"], "id": clean(cs[0].strip("*` "), 40),
                         "tried": clean(cs[1], 160), "happened": clean(cs[2] if len(cs) > 2 else "", 260),
                         "scope_guard": clean(cs[3], 200) if len(cs) > 3 else "", "reopen": "",
                         "source": src_ref(SRC["ledger"], ln, blobs)})
    # §3d numbered list: the instruments that lied.
    in_3d = False
    for i, line in enumerate(led.splitlines(), 1):
        if line.startswith("### 3d"):
            in_3d = True
            continue
        if in_3d and line.startswith("#"):
            break
        m = re.match(r"^\s*(\d+)\.\s+\*\*(.+?)\*\*\s*[—-]\s*(.+)$", line) if in_3d else None
        if m:
            rows.append({"kind": "instrument-that-lied", "section": "ATTEMPTS-LEDGER §3d", "id": f"LIED-{m.group(1)}",
                         "tried": clean(m.group(2), 120), "happened": clean(m.group(3), 300), "scope_guard": "",
                         "reopen": "never as primary instrument", "source": src_ref(SRC["ledger"], i, blobs)})
    # LESSONS.md: | # | lesson (plain language) | root cause | became mechanism | receipts |
    for t in tables(read(SRC["lessons"])):
        for ln, cs in t["rows"]:
            if len(cs) < 4 or not re.match(r"^\d+$", cs[0].strip("*` ")):
                continue
            rows.append({"kind": "lesson", "section": t["section"], "id": f"LESSON-{cs[0].strip('*` ')}",
                         "tried": clean(cs[1], 260), "happened": "root cause: " + clean(cs[2], 220),
                         "scope_guard": "became mechanism: " + clean(cs[3], 220), "reopen": "",
                         "source": src_ref(SRC["lessons"], ln, blobs) + (" · receipts: " + clean(cs[4], 120) if len(cs) > 4 and cs[4].strip() else "")})
    # TRIED-RESULTS, GRAVEYARD, KILL-CARDS (JSON).
    try:
        for r in json.loads(read(SRC["tried"])).get("rows", []):
            rows.append({"kind": "tried-result", "section": "TRIED-RESULTS-COMPACT", "id": str(r.get("id")),
                         "tried": clean(str(r.get("tried")).replace("_", " "), 120),
                         "happened": clean(str(r.get("result")).replace("_", " "), 260),
                         "scope_guard": f"class {r.get('class')}; reuse: {clean(str(r.get('reuse', '')).replace('_', ' '), 120)}",
                         "reopen": "re-run on its class rule (UNREAD = re-run; SCARCITY = budget; PHYSICS = stated condition)",
                         "source": src_ref(SRC["tried"], None, blobs) + (f" src: {clean(str(r['src']), 60)}" if r.get("src") else "")})
    except ValueError:
        pass
    try:
        for c in json.loads(read(SRC["graveyard"])).get("cards", []):
            rows.append({"kind": "graveyard", "section": "GRAVEYARD-INDEX", "id": str(c.get("id")),
                         "tried": clean(str(c.get("name")).replace("_", " "), 120),
                         "happened": f"burial {c.get('burial')} · class {c.get('class')}" + (f" · corrected: {clean(str(c['corrected']), 120)}" if c.get("corrected") else ""),
                         "scope_guard": f"residual value: {clean(str(c.get('residual')).replace('_', ' '), 120)}", "reopen": "",
                         "source": src_ref(SRC["graveyard"], None, blobs)})
    except ValueError:
        pass
    try:
        for hcard in json.loads(read(SRC["kill_cards"])).get("hypotheses", []):
            rows.append({"kind": "kill-card", "section": "HYPOTHESIS-KILL-CARDS", "id": str(hcard.get("id")),
                         "tried": clean(str(hcard.get("claim") or hcard.get("name")), 200),
                         "happened": f"status {hcard.get('status')}",
                         "scope_guard": "kill if: " + clean("; ".join(map(str, hcard.get("kill_if", []))), 200),
                         "reopen": "advance if: " + clean("; ".join(map(str, hcard.get("advance_if", []))), 200),
                         "source": src_ref(SRC["kill_cards"], None, blobs)})
    except ValueError:
        pass
    # ASTRA's knowledge-register records (PR #3459): per-experiment question / why / method /
    # result / lesson / limits / reopen, read from pinned git objects. The SEAM: the reader is
    # the depth, this register is the breadth; each record becomes one row here that names the
    # reader as the place to open.
    for p in sorted((REPO / "workflow" / "knowledge-register" / "records").glob("*.json"), key=lambda p: p.as_posix()):
        try:
            rec = json.loads(p.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            continue
        rel = p.relative_to(REPO).as_posix()
        refs = rec.get("source_refs") or []
        ref0 = refs[0] if refs and isinstance(refs[0], dict) else {}
        src = src_ref(rel, None, blobs)
        if ref0.get("path"):
            src += f" → `{ref0['path']}`@{str(ref0.get('git_commit', ''))[:10]}"
        # ASTRA CONNECTION_FAIL (2026-09-06 01:58Z, E065): a shortened navigation row must never
        # pose as the record. The row is an explicitly marked POINTER carrying the first
        # limitation verbatim; the COMPLETE record (method, result, lesson, every limitation,
        # reopen condition, relationships, source identity) is rendered untruncated in
        # registers/KNOWLEDGE-RECORDS.md, and the reader command is named beside it.
        rid = str(rec.get("id", p.stem))
        limits = [str(x) for x in rec.get("limitations", []) or []]
        first_limit = clean(limits[0], 240) if limits else "(no limitation recorded)"
        more = f" (+{len(limits) - 1} more in the full record)" if len(limits) > 1 else ""
        rows.append({"kind": "knowledge-record", "section": "knowledge-register/records", "id": rid,
                     "tried": clean(str(rec.get("question", "")), 240),
                     "happened": "POINTER (incomplete by design) — result: " + clean(str(rec.get("result", "")), 200)
                                 + f" → full record: `registers/KNOWLEDGE-RECORDS.md` #{rid}",
                     "scope_guard": "first limitation, verbatim: " + first_limit + more,
                     "reopen": clean(str(rec.get("reopen_when", "")), 200) + f" · open: python scripts/research_memory.py show {rid}",
                     "source": src, "record": rec, "record_path": rel})
    rows += harvest_surfaces(blobs)
    for n, r in enumerate(rows, 1):
        r["lid"] = f"L-{n:04d}"
        r["tags"] = tags_for(" ".join(str(r.get(k, "")) for k in ("id", "tried", "happened", "scope_guard", "reopen", "section")))
    return rows


def retracted_tokens_in(text: str) -> list[str]:
    """Retracted register values quoted (whole-token) in a harvested row. The mark travels with the
    row so a reader who lands on it from `dock ask` sees the ban before the number."""
    hits: list[str] = []
    toks = set(NUM_TOKEN.findall(text))
    for v in rr.value_rows():
        for n in v.numbers:
            if n in toks or ("+" + n) in toks or ("-" + n) in toks:
                hits.append(n)
    return sorted(set(hits))


def _mark(marks: list[str]) -> str:
    return ("QUOTES RETRACTED " + ", ".join(marks) + " — banned from citation; see CLAIMS") if marks else ""


def harvest_surfaces(blobs: dict[str, str]) -> list[dict]:
    """The 22 catalogued-but-unharvested markdown surfaces → LEARNINGS rows of kind `surface:<id>`.
    Table rows: id = first cell, `tried` = the first column, `happened` = header→cell pairs.
    Prose-only files: one row per heading with the first paragraph beneath it. Rows quoting a retracted
    value are marked, never dropped (the quote is history; the ban is the register's)."""
    rows: list[dict] = []
    for sid, rel in SURFACES.items():
        text = read(rel)
        if not text:
            continue
        kind = f"surface:{sid}"
        ts = tables(text)
        for t in ts:
            hdr = t["header"]
            for ln, cs in t["rows"]:
                if len(cs) < 2 or not any(cs):
                    continue
                pairs = [f"{clean(h, 28)}: {clean(c, 120)}" for h, c in zip(hdr[1:], cs[1:]) if c.strip()]
                body = " · ".join(pairs) if pairs else clean(" ".join(cs[1:]), 260)
                rows.append({"kind": kind, "section": t["section"] or Path(rel).stem, "id": clean(cs[0].strip("*` "), 40) or f"row L{ln}",
                             "tried": clean(f"{hdr[0]}: {cs[0]}" if hdr and hdr[0] else cs[0], 160), "happened": clean(body, 300),
                             "scope_guard": _mark(retracted_tokens_in(" ".join(cs))), "reopen": "", "source": src_ref(rel, ln, blobs)})
        # ASTRA 2026-09-06 08:23Z CHANGES_REQUESTED: a file with tables ALSO has bullet initiatives
        # (STRATEGY-ATLAS: 18 table rows + 26 `- **T1 …** (dates): what. USE/LESSON: …` records);
        # "tables else headings" dropped every one of them. Mixed format: harvest tables, then every
        # top-level bullet outside a table (kept whole, up to 600 chars, so why/result/lesson and the
        # qualifications survive), then headings+first paragraph only for files with neither.
        lines = text.splitlines()
        table_lines = {ln for t in ts for ln, _ in t["rows"]} | {t["line"] for t in ts}
        section = ""
        n_bullets = 0
        for i, line in enumerate(lines, 1):
            if line.startswith("#"):
                section = line.lstrip("# ").strip()
                continue
            if i in table_lines or line.lstrip().startswith("|"):
                continue
            m = re.match(r"^[-*] (.+)$", line)     # top-level bullets; nested lines ride with their parent
            if not m:
                continue
            body = m.group(1).strip()
            for nxt in lines[i:]:
                if re.match(r"^\s+[-*] ", nxt) or (nxt.startswith("  ") and nxt.strip()):
                    body += " " + nxt.strip()
                else:
                    break
            if len(body) < 40:
                continue
            head = re.match(r"^\*\*([^*]{1,80})\*\*", body)
            rows.append({"kind": kind, "section": section or Path(rel).stem, "id": clean(head.group(1), 40) if head else clean(body, 40),
                         "tried": clean(head.group(1), 160) if head else clean(body, 160), "happened": clean(body, 600),
                         "scope_guard": _mark(retracted_tokens_in(body)), "reopen": "", "source": src_ref(rel, i, blobs)})
            n_bullets += 1
        if ts or n_bullets:
            continue
        for i, line in enumerate(lines, 1):
            if not re.match(r"^#{1,4} ", line):
                continue
            head = line.lstrip("# ").strip()
            para: list[str] = []
            for nxt in lines[i:]:
                if nxt.startswith("#"):
                    break
                if nxt.strip():
                    para.append(nxt.strip())
                elif para:
                    break
            if not para:
                continue
            body = " ".join(para)
            rows.append({"kind": kind, "section": Path(rel).stem, "id": clean(head, 40), "tried": clean(head, 160),
                         "happened": clean(body, 300), "scope_guard": _mark(retracted_tokens_in(body)), "reopen": "",
                         "source": src_ref(rel, i, blobs)})
    return rows


def surface_coverage() -> dict:
    """How many of the catalogued inventory surfaces the harvest reads. A count, not a verdict:
    JSON status packs are pointed at from MANIFEST/TOOLS, not mined for rows."""
    master = json.loads(read(MASTER_INDEX) or "{}")
    read_by_sri = set(SRC.values()) | set(SURFACES.values()) | {
        CATALOG.relative_to(REPO).as_posix(), LABELS.relative_to(REPO).as_posix(), CURATED.relative_to(REPO).as_posix()}
    tally: Counter = Counter()
    unharvested_md: list[str] = []
    for e in master.get("inventories", []):
        p = e["path"]
        if p in read_by_sri:
            tally["harvested"] += 1
        elif p.startswith("workflow/inventories/sri/"):
            tally["sri-output"] += 1
        elif p in NOT_A_SOURCE or p.startswith("workflow/knowledge-register/"):
            tally["routing"] += 1
        elif p.endswith(".json"):
            tally["json-pack-pointer-only"] += 1
        else:
            tally["unharvested-markdown"] += 1
            unharvested_md.append(p)
    return {"catalogued": len(master.get("inventories", [])), **dict(sorted(tally.items())), "unharvested_markdown": unharvested_md}


# ---------------------------------------------------------------- harvest: CLAIMS
_BASENAMES: dict[str, list[str]] | None = None


def basename_map(blobs: dict[str, str]) -> dict[str, list[str]]:
    """basename -> tracked paths, so a producer named by bare filename (`eval.py`) resolves."""
    global _BASENAMES
    if _BASENAMES is None:
        m: dict[str, list[str]] = defaultdict(list)
        for p in blobs:
            m[Path(p).name].append(p)
        _BASENAMES = dict(m)
    return _BASENAMES


COMMAND_RE = re.compile(r"^(python|py|git|gh|uv|pip|powershell|pwsh|\.\\|\./)\b")


def classify_producers(spans: list[str], blobs: dict[str, str]) -> tuple[list[str], list[str], list[str], list[str]]:
    """Backticked spans -> (repo paths that exist, off-repo paths, commands, unresolved names)."""
    repo, off, cmds, unresolved = [], [], [], []
    bm = basename_map(blobs)
    for s in spans:
        s = s.strip()
        if COMMAND_RE.match(s):
            cmds.append(s)
        elif re.match(r"^[A-Za-z]:[\\/]|^https?://|^~|^/", s):
            off.append(s)
        elif "/" in s or "\\" in s:
            (repo if (REPO / s).exists() else unresolved).append(s)
        elif re.search(r"\.\w{2,5}$", s):
            hits = bm.get(s, [])
            if len(hits) == 1:
                repo.append(hits[0])
            else:
                unresolved.append(s)
    return repo, off, cmds, unresolved


def verify_claim(value: str, spans: list[str], today: str, blobs: dict[str, str]) -> tuple[str, str]:
    """(status, how-to-recheck). Status is about WHERE the number can be read today:
    VERIFIED-AT-ARTIFACT — its numeric tokens were found in a named repo artifact;
    UNVERIFIABLE-HERE — the producer is a command or an off-repo path (re-run / open elsewhere);
    RECEIPT-WEAK — no producer resolves to a repo artifact carrying the tokens."""
    toks = [t.replace(",", "") for t in NUM_TOKEN.findall(value)]
    repo, off, cmds, unresolved = classify_producers(spans, blobs)
    if not toks:
        return "RECEIPT-WEAK", "no numeric token in the value cell"
    for p in repo:
        f = REPO / p
        if f.is_file() and f.suffix.lower() in {".md", ".json", ".jsonl", ".csv", ".txt", ".py"}:
            try:
                text = f.read_text(encoding="utf-8", errors="replace").replace(",", "")
            except OSError:
                continue
            if all(t.lstrip("+-−") in text for t in toks):
                return f"VERIFIED-AT-ARTIFACT {today}", f"tokens found in `{p}`"
    if cmds:
        return "UNVERIFIABLE-HERE", "producer is a command — re-run: " + clean("; ".join(cmds), 140)
    if off:
        return "UNVERIFIABLE-HERE", "producer is off-repo: " + clean("; ".join(off), 120)
    if repo:
        return "RECEIPT-WEAK", "named artifact exists but does not carry the tokens: " + clean("; ".join(repo), 120)
    if unresolved:
        return "RECEIPT-WEAK", "producer name does not resolve to one tracked file: " + clean("; ".join(unresolved), 120)
    return "RECEIPT-WEAK", "no producer named in the row"


def qualify_claims(rows: list[dict], cur: dict, blobs: dict[str, str]) -> None:
    """Attach reviewed caveats without changing original quantities or receipt status."""
    for q in cur.get("claim_qualifications", []):
        prefix = src_ref(q["target_path"], q["target_line"], blobs)
        matches = [r for r in rows if r["source"].startswith(prefix)
                   and r["claim"] == q["expected_claim"] and r["value"] == q["expected_value"]]
        evidence = REPO / q["evidence_path"]
        if len(matches) != 1 or not evidence.is_file():
            raise ValueError("Claim qualification target/evidence no longer resolves uniquely")
        if hashlib.sha256(evidence.read_bytes().replace(b"\r\n", b"\n")).hexdigest() != q["evidence_sha256_lf"]:
            raise ValueError("Claim qualification evidence changed; review before rebuilding")
        matches[0]["method"] += " ; QUALIFICATION: " + clean(q["note"], 400)
        matches[0]["source"] += " ; qualification: " + src_ref(q["evidence_path"], None, blobs)


def harvest_claims(blobs: dict[str, str], today: str) -> list[dict]:
    rows: list[dict] = []
    # NUMBERS-INVENTORY: every table; the quantity cell is the one with the most digits.
    num = read(SRC["numbers"])
    # NUMBERS-INVENTORY names producers per SECTION, not per row: the section heading carries the
    # source (`git ls-tree origin/main`, `RELIABILITY-MANIFEST.json`, `eval.py`) and each top-level
    # section has a "How to get them" subsection with the commands. A row inherits both.
    howto: dict[str, list[str]] = defaultdict(list)
    cur_top, in_howto = "", False
    for line in num.splitlines():
        m_top = re.match(r"^##\s+(\d+)\.", line)
        if m_top:
            cur_top, in_howto = m_top.group(1), False
            continue
        if re.match(r"^###\s+\d+\.\d+\s+How to get them", line):
            in_howto = True
            continue
        if line.startswith("### "):
            in_howto = False
        if in_howto and cur_top:
            howto[cur_top] += BACKTICK_PATH.findall(line)
            # the commands live in fenced ```bash blocks, one per line, not in inline backticks
            stripped = line.strip()
            if COMMAND_RE.match(stripped) and not stripped.startswith("```"):
                howto[cur_top].append(stripped.split("#")[0].strip())
    for t in tables(num):
        sec_spans = BACKTICK_PATH.findall(t["section"])
        m_sec = re.match(r"^(\d+)\.", t["section"])
        inherited = sec_spans + (howto.get(m_sec.group(1), []) if m_sec else [])
        for ln, cs in t["rows"]:
            if len(cs) < 3:
                continue
            qty = max(cs[1:], key=lambda c: len(NUM_TOKEN.findall(c)))
            if not NUM_TOKEN.findall(qty):
                continue
            spans = BACKTICK_PATH.findall(" ".join(cs)) + inherited
            paths = [p for p in spans if "/" in p or "\\" in p or re.search(r"\.\w{2,5}$", p)]
            state = next((c for c in cs if c.strip() in {"MEASURED", "AVAILABLE", "BLIND"}), "")
            if state == "BLIND":
                status, how = "UNVERIFIABLE-HERE", "declared BLIND by the inventory (not obtainable from data)"
            else:
                status, how = verify_claim(qty, spans, today, blobs)
            rows.append({"claim": clean(cs[1] if cs[1] != qty else cs[0], 120), "value": clean(qty, 160),
                         "source": src_ref(SRC["numbers"], ln, blobs) + (" → " + ", ".join(f"`{p}`" for p in paths[:2]) if paths else ""),
                         "method": f"NUMBERS-INVENTORY state {state or '-'}; {how}",
                         "status": status, "used_in": t["section"][:60]})
    # METRICS-INVENTORY values.
    try:
        for m in json.loads(read(SRC["metrics"])).get("metrics", []):
            if m.get("value") is None:
                continue
            srcs = str(m.get("source", ""))
            # "EQUATIONS b=217.55" names the canon file by stem, not by path
            paths = [srcs] if "/" in srcs else ([SRC["equations"]] if srcs.upper().startswith("EQUATIONS") else [])
            rows.append({"claim": clean(f"{m.get('name')} — {m.get('definition', '')}", 120), "value": f"{m['value']} {m.get('units', '')}".strip(),
                         "source": src_ref(SRC["metrics"], None, blobs) + (" → " + ", ".join(f"`{p}`" for p in paths) if paths else ""),
                         "method": clean(str(m.get("notes", "")), 100) or "read the named equation file",
                         "status": verify_claim(str(m["value"]), paths, today, blobs)[0], "used_in": "METRICS-INVENTORY"})
    except ValueError:
        pass
    # EQUATIONS.md constants (first table = the b-curves) and every other table cell with a number.
    eq = read(SRC["equations"])
    for t in tables(eq):
        for ln, cs in t["rows"]:
            if len(cs) < 2 or not NUM_TOKEN.findall(cs[0] + cs[1]):
                continue
            rows.append({"claim": clean(f"{t['section']}: {cs[0]}", 120), "value": clean(cs[1], 120),
                         "source": src_ref(SRC["equations"], ln, blobs), "method": clean(" · ".join(cs[2:]), 140) or "canon table",
                         "status": f"VERIFIED-AT-ARTIFACT {today}", "used_in": "canon/EQUATIONS.md"})
    # RETRACTIONS: every value row is a claim with status RETRACTED (exempt from the source gate).
    for r in rr.value_rows():
        rows.append({"claim": clean(r.raw, 120), "value": ", ".join(r.numbers + tuple(h[:12] for h in r.hashes)) or "(see row)",
                     "source": src_ref(SRC["retractions"], None, blobs), "method": f"use instead: {clean(r.use_instead, 120)}",
                     "status": "RETRACTED", "used_in": f"retracted {r.retracted}"})
    for n, r in enumerate(rows, 1):
        r["cid"] = f"c-{n:03d}"
    return rows


# ---------------------------------------------------------------- harvest: METHODS / TOOLS / DECISIONS / OPEN / TOMBSTONES
def harvest_methods(cur: dict, blobs: dict[str, str], today: str) -> list[dict]:
    out = []
    for m in cur.get("methods", []):
        impl = m.get("implemented_in", "")
        test = m.get("test", "")
        status = m.get("status", "proposed")
        if not impl:
            status = "research note (no implementation pointer)"
        elif impl not in blobs:
            status = f"BROKEN POINTER ({impl} not tracked)"
        out.append({**m, "status": status, "impl_ref": src_ref(impl, None, blobs) if impl else "—",
                    "test_ref": src_ref(test, None, blobs) if test else "—", "src_ref": src_ref(m.get("source", ""), None, blobs),
                    "verified": today})
    return out


def harvest_tools(blobs: dict[str, str], today: str) -> list[dict]:
    outputs: dict[str, dict] = {}
    try:
        for t in json.loads(read(SRC["tools_output"])).get("tools", []):
            if t.get("path"):
                outputs[t["path"]] = t
    except ValueError:
        pass
    rows = []
    if CATALOG.exists():
        for line in CATALOG.read_text(encoding="utf-8", errors="replace").splitlines():
            try:
                r = json.loads(line)
            except ValueError:
                continue
            p = r.get("path", "")
            if not (p.startswith("scripts/") or p.startswith("ptcg-agent/harness/")) or not p.endswith(".py"):
                continue
            name = Path(p).name
            if name.startswith("test_") or name == "conftest.py":
                continue
            text = read(p)
            money = "maybe (names an API key or paid service)" if re.search(r"ANTHROPIC|OPENAI|api_key|KAGGLE_KEY|billing", text) else "no"
            usage = next((ln.strip() for ln in text.splitlines()[:60] if re.match(r"^\s*python\s+\S+", ln)), f"python {p}")
            o = outputs.get(p, {})
            rows.append({"path": p, "title": clean(r.get("title") or name, 110), "invocation": clean(usage, 110),
                         "first_commit": (r.get("first_commit") or "")[:10], "output_status": o.get("output_status", ""),
                         "last_output": clean(str(o.get("last_output_summary", "")), 120), "money": money,
                         "source": src_ref(p, None, blobs), "verified": today})
    # The catalog is a snapshot; tools added after it was generated (build_sri.py, dock.py,
    # retraction_scan.py on 2026-09-05/06) were invisible here and in the timeline until this union
    # with git's own file list. Title = the module docstring's first line.
    known = {r["path"] for r in rows}
    for p in sorted(blobs):
        if p in known or not p.endswith(".py"):
            continue
        if not (p.startswith("scripts/") or p.startswith("ptcg-agent/harness/")) or p.count("/") != (1 if p.startswith("scripts/") else 2):
            continue
        name = Path(p).name
        if name.startswith("test_") or name == "conftest.py":
            continue
        text = read(p)
        m = re.search(r'^\s*(?:r|u)?"""\s*(.+?)\s*$', text, re.M)
        title = clean(m.group(1).strip('"'), 110) if m else name
        money = "maybe (names an API key or paid service)" if re.search(r"ANTHROPIC|OPENAI|api_key|KAGGLE" + r"_KEY|billing", text) else "no"
        usage = next((ln.strip() for ln in text.splitlines()[:60] if re.match(r"^\s*python\s+\S+", ln)), f"python {p}")
        o = outputs.get(p, {})
        rows.append({"path": p, "title": title, "invocation": clean(usage, 110), "first_commit": "",
                     "output_status": o.get("output_status", ""), "last_output": clean(str(o.get("last_output_summary", "")), 120),
                     "money": money, "source": src_ref(p, None, blobs), "verified": today})
    rows.sort(key=lambda x: x["path"])
    return rows


def history_is_complete() -> bool:
    """Is this checkout's history whole enough to say when a file was created?

    ROACH 2026-09-06 10:35Z and 11:01Z: `test_timeline_register` failed twice in CI with
    `scripts/build_sri.py` attributed first to #3478's squash and then to #3488's — the attribution
    followed whatever had most recently landed on main. Neither ordering fix could work, because the
    history itself is truncated: this repository's own `ci.yml` recorded on 2026-09-04 (diagnostic
    run 33922175784) that the runner repo is SHALLOW at test time — `is-shallow-repository` = true,
    `.git/shallow` present — DESPITE `fetch-depth: 0`. Under a graft every path looks as though it
    were added at the boundary commit, so a creation date read there is not late or approximate, it
    is wrong.

    A register that would rather say nothing than say something false: when the history is
    truncated the timeline still lists every tool and record, and marks the date and the reason
    UNKNOWN instead of printing the boundary commit's subject as the reason a tool exists.

    ASTRA 2026-09-06 11:15Z: the first version returned `sh(...) != "true"`, and `sh()` returns an
    empty string on a NON-ZERO exit — so a git query that FAILED was read as "history is complete"
    and the register went on to print provenance it could not know. Only an explicit successful
    "false" now means complete; a failure, an empty answer or anything unrecognised means unknown,
    and unknown withholds."""
    if (REPO / ".git" / "shallow").exists():
        return False
    r = subprocess.run(["git", "rev-parse", "--is-shallow-repository"], cwd=str(REPO),
                       capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120)
    return r.returncode == 0 and r.stdout.strip() == "false"


UNKNOWN_HISTORY = "unknown — truncated checkout"


def first_adds() -> dict[str, tuple[str, str, str]]:
    """path -> (date, commit, subject) of the commit with the EARLIEST COMMITTER DATE that adds it,
    from ONE git walk (12k lines in ~1 s) instead of one `git log` per tool.

    Read this precisely: it is the earliest committer date VISIBLE IN THIS HISTORY, not a claim
    about when the work was done. Committer dates can be rewritten by a rebase, author dates can be
    backdated outright (which is why this no longer uses them), and a squash replaces the original
    commits entirely. No inference about creation, effort or order follows from the string.

    ROACH 2026-09-06 10:35Z, CI run 34026871919: the previous version kept the first row the walk
    emitted. `--reverse` reverses git's default ordering, which over a branchy graph is topological
    and NOT chronological, so on a merge graph — which CI builds for every PR — a later squash
    commit can be emitted before the commit that truly introduced a file. `scripts/build_sri.py`
    was then dated to #3478's squash and given ITS subject as the reason the tool was created. The
    timeline register's whole promise is when a tool was created and why, so an order-dependent
    answer is unacceptable even when it happens to be right. Take the earliest COMMIT TIMESTAMP
    instead: deterministic in any topology, linear or merged.

    After a squash merge the original authoring commits are unreachable from main, so the honest
    answer is the earliest commit in THIS history that adds the path — the squash, whose subject is
    the PR title. That is the intended reading; it simply no longer varies with traversal order."""
    best: dict[str, tuple[int, str, str, str]] = {}
    cur: tuple[int, str, str, str] | None = None
    # %ct/%cd are COMMITTER dates. ASTRA 2026-09-06 11:15Z: the first version used %at/%ad (AUTHOR
    # dates) while calling them commit timestamps. Author dates can be backdated at will and are not
    # a causal order of first introduction; committer dates at least record when the commit entered
    # this history. Neither is a claim about when the work was really done — see the column note.
    # Read full identities; format the display ourselves. %h depends on core.abbrev
    # and the local object database, so Windows and CI emitted different rows.
    for line in sh(["git", "log", "--diff-filter=A", "--name-only", "--format=%x00%ct|%cd|%H|%s", "--date=short"]).splitlines():
        if line.startswith("\0"):
            parts = line[1:].split("|", 3)
            try:
                cur = (int(parts[0]), parts[1], parts[2], parts[3] if len(parts) > 3 else "") if len(parts) >= 3 else None
            except ValueError:
                cur = None
            continue
        p = line.strip()
        if p and cur and (p not in best or cur[0] < best[p][0]):
            best[p] = cur
    return {p: (v[1], v[2][:10], v[3]) for p, v in best.items()}


def latest_nonmerge_path_date(path: str, ref: str = "HEAD") -> str:
    """Latest UTC committer date among non-merge path changes in reachable history.

    This is history metadata, not current-blob age or an experiment execution date.
    Full traversal avoids git log -1 selecting a different simplified parent history
    in GitHub's synthetic merge despite identical input file bytes.
    """
    if not history_is_complete():
        return UNKNOWN_HISTORY
    raw = sh(["git", "log", "--full-history", "--no-merges", "--format=%ct", ref, "--", path])
    if not raw.strip():
        return "—"
    try:
        return datetime.fromtimestamp(max(int(x) for x in raw.splitlines()), timezone.utc).date().isoformat()
    except (ValueError, OverflowError, OSError):
        return "—"


def harvest_timeline(tools: list[dict], blobs: dict[str, str]) -> list[dict]:
    """Jon 2026-09-05: "timelines for when we created tools and why we created them" (and for the
    write-up). One row per tool and per knowledge record: the date it entered git, the commit, and
    the recorded WHY: commit subject for tools; the record's why/question field for knowledge,
    falling back to its commit subject. These are attributed descriptions, not assessments.

    On a truncated checkout (see history_is_complete) the date and reason are marked UNKNOWN rather
    than filled from the graft boundary, which would name the wrong commit as the reason a tool
    exists. The rows themselves stay: what we have is still listed, only the provenance is withheld."""
    whole = history_is_complete()
    adds = first_adds() if whole else {}
    rows: list[dict] = []
    for t in tools:
        d, h, s = adds.get(t["path"], ("", "", ""))
        m = re.search(r"\(#(\d+)\)", s)
        rows.append({"date": d or (t.get("first_commit") if whole else "") or ("—" if whole else UNKNOWN_HISTORY),
                     "kind": "tool", "what": f"`{t['path']}`",
                     "why": (clean(re.sub(r"\s*\(#\d+\)\s*$", "", s), 200) or "(no commit subject in this history)")
                            if whole else UNKNOWN_HISTORY,
                     "commit": h or "—", "pr": f"#{m.group(1)}" if m else "—", "source": src_ref(t["path"], None, blobs)})
    rec_dir = REPO / "workflow" / "knowledge-register" / "records"
    if rec_dir.exists():
        for p in sorted(rec_dir.glob("*.json"), key=lambda p: p.as_posix()):
            rel = p.relative_to(REPO).as_posix()
            d, h, s = adds.get(rel, ("", "", ""))
            try:
                rec = json.loads(p.read_text(encoding="utf-8"))
            except ValueError:
                rec = {}
            m = re.search(r"\(#(\d+)\)", s)
            rows.append({"date": d or ("—" if whole else UNKNOWN_HISTORY), "kind": "knowledge-record",
                         "what": f"`{rel}` {rec.get('id', p.stem)}",
                         "why": clean(str(rec.get("why") or rec.get("question") or s), 200) or (
                             "—" if whole else UNKNOWN_HISTORY),
                         "commit": h or "—", "pr": f"#{m.group(1)}" if m else "—", "source": src_ref(rel, None, blobs)})
    rows.sort(key=lambda r: (r["date"] in ("—", UNKNOWN_HISTORY), r["date"], r["kind"], r["what"]))
    return rows


def harvest_decisions(blobs: dict[str, str]) -> list[dict]:
    rows = []
    for t in tables(read(SRC["decisions"])):
        hdr = " ".join(t["header"]).lower()
        body = list(t["rows"])
        if "decision" not in hdr:
            # DECISIONS.md's second block (1,702 rulings) has no header row: its first line is a
            # ruling whose first cell is a date. Treat that line as data, not as a header.
            if t["header"] and re.match(r"^\d{2,4}-\d\d", t["header"][0].strip()):
                body.insert(0, (t["line"], t["header"]))
            else:
                continue
        for ln, cs in body:
            if len(cs) < 2:
                continue
            m = re.search(r"\*\*(.+?)\*\*", cs[1])
            rows.append({"date": clean(cs[0], 24), "decision": clean(m.group(1) if m else cs[1], 150),
                         "why": clean(cs[2], 140) if len(cs) > 2 else "", "reverse_if": clean(cs[4], 100) if len(cs) > 4 else "",
                         "source": src_ref(SRC["decisions"], ln, blobs)})
    return rows


def harvest_open(learnings: list[dict], blobs: dict[str, str]) -> list[dict]:
    rows = []
    for L in learnings:
        text = f"{L['happened']} {L['scope_guard']}".upper()
        if L["kind"] == "ledger" and L["id"].startswith("GR-") and "OPEN" in text:
            rows.append({"item": f"{L['id']} — {L['tried']}", "why": "ledger row status contains OPEN", "unblock": clean(L["scope_guard"] or L["happened"], 160), "source": L["source"]})
        elif L["kind"] == "tried-result" and "UNREAD" in text:
            rows.append({"item": f"{L['id']} — {L['tried']}", "why": "class UNREAD: the instrument could not resolve it", "unblock": "re-run with a resolving instrument", "source": L["source"]})
        elif L["kind"] == "dead-end" and L["reopen"] and L["reopen"] not in {"—", "-"}:
            rows.append({"item": f"{L['id']} — {L['tried']}", "why": "closed with a named reopen condition", "unblock": L["reopen"], "source": L["source"]})
        elif L["kind"] == "kill-card" and "FROZEN" in text:
            rows.append({"item": f"{L['id']} — {L['tried']}", "why": L["happened"], "unblock": L["reopen"], "source": L["source"]})
    for t in tables(read(SRC["improvement"])):
        for ln, cs in t["rows"]:
            if len(cs) >= 3 and "SCARCITY" in cs[2].upper():
                rows.append({"item": clean(cs[1], 120), "why": "CLOSED-SCARCITY: not spent, not refuted", "unblock": clean(cs[3] if len(cs) > 3 else cs[2], 140),
                             "source": src_ref(SRC["improvement"], ln, blobs)})
    for n, r in enumerate(rows, 1):
        r["oid"] = f"O-{n:03d}"
    return rows


def harvest_tombstones(blobs: dict[str, str]) -> list[dict]:
    rows = []
    # ASTRA 2026-09-06 08:23Z: two tombstone states, never one label. The register's original rows
    # are "current vs archive (files kept)": the surface stays in place, marked, and a successor
    # names it. The retire rows (#3477, #3480) begin their third cell with ARCHIVED-COPY-IN-BAG and
    # name the destination: the file is REMOVED from the tree and lives at that path (and in git
    # history at the blob the second cell names). The destination is read from the row, not typed.
    for t in tables(read(SRC["supersession"])):
        for ln, cs in t["rows"]:
            if len(cs) < 3:
                continue
            succ = cs[2].strip()
            if succ.startswith("ARCHIVED-COPY-IN-BAG"):
                dest = succ.split("·", 1)[1].strip() if "·" in succ else succ
                rows.append({"from": clean(cs[1], 160), "to": f"REMOVED FROM TREE → {clean(dest, 160)}", "date": clean(cs[0], 12),
                             "why": clean(cs[3] if len(cs) > 3 else "", 200), "replaced_by": "— (retired; restore command in the why column)",
                             "source": src_ref(SRC["supersession"], ln, blobs)})
            else:
                rows.append({"from": clean(cs[1], 120), "to": "IN PLACE, marked (file kept)", "date": clean(cs[0], 12), "why": clean(cs[3] if len(cs) > 3 else "", 120),
                             "replaced_by": clean(succ, 120), "source": src_ref(SRC["supersession"], ln, blobs)})
    hist = REPO / "workflow" / "history"
    if hist.is_dir():
        for p in sorted(hist.glob("*.md"), key=lambda p: p.as_posix()):
            rel = p.relative_to(REPO).as_posix()
            rows.append({"from": "(see banner in file)", "to": f"`{rel}`", "date": "", "why": "onboarding cut 2026-09-05 (#3441): history moved out of the read path",
                         "replaced_by": "the current file it names", "source": src_ref(rel, None, blobs)})
    # External paths are observations, not ambient build inputs. A clean Linux checkout
    # must reproduce the same history even when this Windows volume is unavailable.
    observations = json.loads(CURATED.read_text(encoding="utf-8")).get("external_archive_observations", [])
    for obs in sorted(observations, key=lambda r: r["archive_manifest"]):
        rows.append({"from": f"legacy display: {obs['legacy_display']}",
                     "to": f"`{obs['archive_manifest']}`", "date": obs["observed_at"],
                     "why": obs["limitation"], "replaced_by": "—",
                     "source": src_ref(CURATED.relative_to(REPO).as_posix(), None, blobs)
                               + f" · {obs['host']} · observed manifest SHA256 {obs['sha256']}"})
    return rows


# ---------------------------------------------------------------- MANIFEST
CLASS_MAP = {"doc": "doc", "code": "code", "config": "config", "data": "data", "test": "test", "log": "log", "media": "media",
             "bundle": "bundle", "archive": "archive", "other": "other"}


def harvest_manifest(cur: dict, blobs: dict[str, str], today: str) -> list[dict]:
    a_by_path = {a["path"]: a for a in cur.get("a_assets", [])}
    cat: dict[str, dict] = {}
    if CATALOG.exists():
        for line in CATALOG.read_text(encoding="utf-8", errors="replace").splitlines():
            try:
                r = json.loads(line)
                cat[r["path"]] = r
            except (ValueError, KeyError):
                continue
    labels: dict[str, dict] = {}
    if LABELS.exists():
        with LABELS.open(encoding="utf-8", errors="replace", newline="") as f:
            for r in csv.DictReader(f):
                labels[r["path"]] = r
    records = []
    n = 0
    paths = sorted(set(labels) | set(a_by_path))
    for p in paths:
        lab = labels.get(p, {})
        label = lab.get("label", "")
        if label == "REFUSED":
            continue
        kind = lab.get("kind") or cat.get(p, {}).get("kind") or "other"
        cls = CLASS_MAP.get(kind, "other")
        if Path(p).name.startswith("test_"):
            cls = "test"
        # The manifest is the KNOWLEDGE inventory: docs, data, config, and the tools under
        # scripts/ + harness/. Tests, logs, media and library code are censused by curate
        # (workflow/curation/labels.csv) and are not repeated here.
        is_tool = cls == "code" and (p.startswith("scripts/") or p.startswith("ptcg-agent/harness/"))
        if cls not in {"doc", "data", "config"} and not is_tool and p not in a_by_path:
            continue
        if p in a_by_path:
            status, value = "canonical", "A"
        elif label == "SUPERSEDED":
            status, value = "superseded", "C"
        elif label == "ARCHIVE-CANDIDATE":
            status, value = "derived" if lab.get("rule_id", "").startswith("duplicate") else "superseded", "C"
        elif label == "KEEP-STATE":
            status, value = "canonical", "B"
        elif label in {"KEEP-PINNED", "KEEP-REFERENCED"}:
            status, value = "evidence", "B"
        elif label == "KEEP-LIVE":
            status, value = ("canonical" if cls in {"code", "config"} else "evidence"), "B"
        else:
            status, value = "unknown", "B"
        if not (REPO / p).exists():
            continue
        c = cat.get(p, {})
        title = c.get("title") or Path(p).name
        why = a_by_path.get(p, {}).get("why") or (clean(re.sub(r"^#+\s*", "", (c.get("lead") or title)).split(". ")[0], 160) + " (auto: first sentence)")
        n += 1
        rec = {"id": f"a-{n:05d}", "path": p, "title": clean(title, 120), "class": cls, "status": status, "value": value,
               "produced_by": (f"seat {c['seat']}" if c.get("seat") else "operator") + (f", first commit {c['first_commit'][:10]}" if c.get("first_commit") else "") + " (git)",
               "inputs": [], "claims": [], "last_verified": today, "why_it_matters": why,
               "blob": blobs.get(p), "curate_label": label, "curate_rule": lab.get("rule_id", ""), "successor": lab.get("successor", "") or None,
               "supersedes": None, "archived_to": None, "archived_why": None}
        if value == "A":
            rec["next_action"] = a_by_path[p].get("next_action", "")
        records.append(rec)
    return records


# ---------------------------------------------------------------- render
def md_table(header: list[str], rows: list[list[str]]) -> list[str]:
    return ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)] + ["| " + " | ".join(r) + " |" for r in rows]


def render_registers(today: str, main: str, learn, claims, methods, tools, decisions, opens, tombs, timeline=None) -> dict[str, str]:
    banner = f"<!-- GENERATED by scripts/build_sri.py from canonical sources on {today} at main {main[:12]}. Do not edit; edit the source it cites. -->\n"
    files: dict[str, str] = {}
    # LEARNINGS
    lines = [banner, "# Learnings register — findings AND failures (every row cites its source line + blob)", "",
             f"{len(learn)} rows harvested: " + ", ".join(f"{k} {v}" for k, v in sorted(Counter(r['kind'] for r in learn).items())) + ".",
             "Failures are the expensive knowledge; the scope guard says what a closed row does NOT prove. Read `workflow/DEAD-ENDS.md`'s 2026-07-31 reclassification before citing any A-row.", ""]
    fixed = ["instrument-that-lied", "lesson", "dead-end", "knowledge-record", "tried-result", "graveyard", "kill-card", "ledger"]
    surface_kinds = sorted({r["kind"] for r in learn if r["kind"].startswith("surface:")})
    for kind in fixed + surface_kinds:
        sub = [r for r in learn if r["kind"] == kind]
        if surface_kinds and kind == surface_kinds[0]:
            lines += ["## History and canon surfaces (harvested table-by-table; `surface:<id>` names the catalogued inventory it came from)", "",
                      "One row per table row or heading of the 2026-08 reconstruction inventories, the canon strategy/measurement pages "
                      "and the index pages. A row marked QUOTES RETRACTED is history that cites a banned value: read CLAIMS before using it.", ""]
        if not sub:
            continue
        lines += [f"## {kind} ({len(sub)})", ""]
        lines += md_table(["#", "id", "tags", "what we tried / believed", "what happened", "scope guard / class", "reopens if", "source"],
                          [[r["lid"], r["id"], " ".join(r.get("tags", [])) or "—", r["tried"], r["happened"], r["scope_guard"] or "—", r["reopen"] or "—", r["source"]] for r in sub])
        lines.append("")
    tag_counts = Counter(t for r in learn for t in r.get("tags", []))
    lines.insert(5, "Tags are retrieval keys derived from each row's own words (never verdicts): " + ", ".join(f"`{t}` {n}" for t, n in sorted(tag_counts.items())) + ". Filter with `python scripts/dock.py ask \"<question>\" --tag <tag>`.")
    files["LEARNINGS.md"] = "\n".join(lines) + "\n"
    # KNOWLEDGE-RECORDS: the complete, untruncated record behind every knowledge-record pointer row
    recs = [r for r in learn if r["kind"] == "knowledge-record" and r.get("record")]
    lines = [banner, "# Knowledge records — complete, untruncated (the record behind each LEARNINGS pointer row)", "",
             f"{len(recs)} records from `workflow/knowledge-register/records/*.json` (ASTRA's reader). Nothing here is shortened: method, result, lesson, every limitation, the reopen condition, relationships and source identity are reproduced in full. Open one with `python scripts/research_memory.py show <id>`.", ""]
    for r in recs:
        rec = r["record"]
        lines += [f"## {r['id']}", "",
                  f"- **question:** {rec.get('question', '')}",
                  f"- **why:** {rec.get('why', '')}",
                  f"- **methodology:** {rec.get('methodology', '')}",
                  f"- **result:** {rec.get('result', '')}",
                  f"- **learn:** {rec.get('learn', '')}"]
        lims = rec.get("limitations", []) or []
        lines.append("- **limitations:**" + ("" if lims else " (none recorded)"))
        lines += [f"  - {x}" for x in lims]
        lines += [f"- **reopen_when:** {rec.get('reopen_when', '')}",
                  f"- **related_ids:** {', '.join(map(str, rec.get('related_ids', []) or []))}",
                  f"- **schema:** {rec.get('schema', 'legacy explanatory note')}",
                  f"- **evidence_status:** {rec.get('evidence_status', 'not recorded; consult the source')}",
                  f"- **producer_seat:** {rec.get('producer_seat', '')}",
                  f"- **interpretation_basis:** {rec.get('interpretation_basis', '')}",
                  f"- **reviewed_at:** {rec.get('reviewed_at', '')}",
                  f"- **recorded_at:** {rec.get('recorded_at', '')}",
                  "- **source_refs:**"]
        for s in rec.get("source_refs", []) or []:
            if isinstance(s, dict):
                loc = s.get("locator") or {}
                locator = (" JSON pointer " + json.dumps(loc["json_pointer"], ensure_ascii=False)
                           if isinstance(loc, dict) and "json_pointer" in loc else
                           f" L{loc.get('line_start')}–{loc.get('line_end')}"
                           if isinstance(loc, dict) and loc.get('line_start') else " (locator not recorded)")
                lines.append(f"  - `{s.get('path', '')}` @ {s.get('git_commit', '')} sha256 {s.get('sha256', '')}"
                             + locator)
        lines += [f"- **record file:** {r['source']}", ""]
    files["KNOWLEDGE-RECORDS.md"] = "\n".join(line.rstrip() for line in lines) + "\n"
    # CLAIMS
    st = Counter(r["status"].split()[0] for r in claims)
    lines = [banner, "# Claims register — every number with its source and verification status", "",
             f"{len(claims)} rows: " + ", ".join(f"{k} {v}" for k, v in sorted(st.items())) + ".",
             "Status is about WHERE the number can be read today, never about whether it is true. RETRACTED rows are banned from citation (register verdict).", ""]
    lines += md_table(["id", "claim (exact wording)", "value", "source of truth", "method / how to re-check", "verified", "status", "used in"],
                      [[r["cid"], r["claim"], r["value"], r["source"], r["method"], today if r["status"].startswith("VERIFIED") else "—", r["status"].split()[0], r["used_in"]] for r in claims])
    files["CLAIMS.md"] = "\n".join(lines) + "\n"
    # METHODS
    lines = [banner, "# Methods register — equations, rules, thresholds, bound to their implementation", "",
             "Definitions are curated interpretations; source pointers locate their evidence. An implementation pointer is not a mathematical or experimental verification.", ""]
    lines += md_table(["#", "name", "definition", "source", "implemented in", "pinned by test", "status", "verified"],
                      [[m["id"], m["name"], clean(m["definition"], 300), m["src_ref"], m["impl_ref"], m["test_ref"], m["status"], m["verified"]] for m in methods])
    files["METHODS.md"] = "\n".join(lines) + "\n"
    # TOOLS
    lines = [banner, "# Tools register — every script under scripts/ and ptcg-agent/harness/ (tests excluded)", "",
             f"{len(tools)} tools. `output status` comes from `workflow/inventories/TOOLS-OUTPUT-EXISTS.json` where a row exists (CODE EXISTS is not completion). First-commit dates from git via the catalog.", ""]
    lines += md_table(["tool", "what (docstring first line)", "invocation", "first commit", "output status", "costs money?", "verified"],
                      [[f"`{t['path']}`", t["title"], f"`{t['invocation']}`", t["first_commit"] or "—", (t["output_status"] + (": " + t["last_output"] if t["last_output"] else "")) or "—", t["money"], t["verified"]] for t in tools])
    files["TOOLS.md"] = "\n".join(lines) + "\n"
    # TIMELINE (Jon 2026-09-05: when we created tools and why)
    if timeline is not None:
        by_month = defaultdict(list)
        for r in timeline:
            by_month[r["date"][:7] if r["date"] not in ("—", UNKNOWN_HISTORY) else "undated"].append(r)
        lines = [banner, "# Timeline register — first recorded appearance of tools and knowledge", "",
                 f"{len(timeline)} rows: " + ", ".join(f"{k} {v}" for k, v in sorted(Counter(r['kind'] for r in timeline).items())) + ". "
                 "The WHY column quotes the first commit subject for tools; knowledge records use their why/question field, falling back to the commit subject. These attributed descriptions are not verified explanations of success. "
                 "The DATE is the earliest COMMITTER date visible in this checkout's history for a commit that adds the path — "
                 "not a claim about when the work was done: a squash-merge carries the merge date, a rebase rewrites committer "
                 "dates, and the original commits may be gone. No inference about creation or effort follows from it.",
                 "" if history_is_complete() else
                 "**This layer was generated on a TRUNCATED checkout** (`.git/shallow` or `is-shallow-repository`), where every path "
                 "appears to be added at the graft boundary. Date and reason are therefore marked "
                 f"`{UNKNOWN_HISTORY}` rather than filled with the boundary commit's subject, which would name the wrong reason a "
                 "tool exists. Regenerate on a full clone to restore provenance.", ""]
        for month in sorted(by_month, key=lambda m: (m == "undated", m)):
            sub = by_month[month]
            lines += [f"## {month} ({len(sub)})", ""]
            lines += md_table(["first-add date", "kind", "what", "recorded context (basis above)", "commit", "PR", "source"],
                              [[r["date"], r["kind"], r["what"], r["why"], r["commit"], r["pr"], r["source"]] for r in sub])
            lines.append("")
        files["TIMELINE.md"] = "\n".join(lines) + "\n"
    # DECISIONS
    by_month: dict[str, list] = defaultdict(list)
    for d in decisions:
        by_month[d["date"][:5] if re.match(r"\d\d-\d\d", d["date"]) else "undated"].append(d)
    lines = [banner, "# Decisions register — every dated ruling in workflow/DECISIONS.md, one line each", "",
             f"{len(decisions)} rulings. Dates are MM-DD as written in the log (2026). Post-08-13 rulings have no source file (B4) and are absent here by construction.", ""]
    for month in sorted(by_month):
        lines += [f"## {month} ({len(by_month[month])})", ""]
        lines += md_table(["date", "decision", "basis", "would reverse if", "source"], [[d["date"], d["decision"], d["why"], d["reverse_if"] or "—", d["source"]] for d in by_month[month]])
        lines.append("")
    files["DECISIONS.md"] = "\n".join(lines) + "\n"
    # OPEN
    lines = [banner, "# Open questions and parked work", "", f"{len(opens)} rows: ledger OPEN rows, UNREAD classes, dead-ends with a named reopen condition, frozen kill cards, scarcity-closed lines.", ""]
    lines += md_table(["#", "question / parked item", "why open", "what would unblock it", "source"], [[o["oid"], o["item"], o["why"], o["unblock"], o["source"]] for o in opens])
    files["OPEN.md"] = "\n".join(lines) + "\n"
    # RETEST-QUEUE: every closed line with a NAMED reopen condition, with the date its source last
    # changed (git). A source that moved after the row was written is a candidate for review, not an
    # automatic reopen (ASTRA: a discovery marks dependants affected; it does not refute or authorize).
    rq = []
    for r in learn:
        cond = (r.get("reopen") or "").strip()
        if not cond or cond in {"—", "-"} or cond.startswith("re-run on its class rule") or cond.startswith("never"):
            continue
        m = re.search(r"`([^`]+)`", r["source"])
        srcp = m.group(1) if m else ""
        last = latest_nonmerge_path_date(srcp) if srcp else ""
        rq.append({"lid": r["lid"], "id": r["id"], "kind": r["kind"], "line": r["tried"], "reopen": cond, "source": r["source"], "last_change": last or "—",
                   "tags": " ".join(r.get("tags", [])) or "—"})
    lines = [banner, "# Retest queue — named reopen conditions and source history", "",
             f"{len(rq)} rows. This queue is generated; nothing here is authorised. A row becomes actionable when its condition is met by evidence on main, and a rerun still needs its own question, allocation and non-author review.",
             "Dates are the latest UTC committer dates of non-merge path changes in reachable history. They are not current-blob modification times, study execution dates, or evidence that a reopen condition is met. Merge-only changes and unverified history do not establish a date.", ""]
    lines += md_table(["#", "id", "kind", "tags", "closed line", "reopens if", "latest non-merge path date (UTC)", "source"],
                      [[q["lid"], q["id"], q["kind"], q["tags"], q["line"], q["reopen"], q["last_change"], q["source"]] for q in rq])
    files["RETEST-QUEUE.md"] = "\n".join(lines) + "\n"
    # TOMBSTONES
    lines = [banner, "# Tombstones — every archive move and supersession (nothing is deleted)", "", f"{len(tombs)} rows.", ""]
    lines += md_table(["from", "to", "date", "why", "replaced by", "source"], [[t["from"], t["to"], t["date"] or "—", t["why"] or "—", t["replaced_by"], t["source"]] for t in tombs])
    files["TOMBSTONES.md"] = "\n".join(lines) + "\n"
    return files


def render_inventory(today: str, main: str, cur: dict, manifest: list[dict]) -> str:
    a = [r for r in manifest if r["value"] == "A"]
    c = [r for r in manifest if r["value"] == "C"]
    b = [r for r in manifest if r["value"] == "B"]
    lines = [f"<!-- GENERATED by scripts/build_sri.py on {today} at main {main[:12]}. Edit CURATED.json for A/D rows; everything else comes from curate labels + the catalog. -->",
             "# Inventory — Pokemon TCG agent (value-ranked)", "", f"**As of:** {today} · **Method:** SRI (curate census + generated registers) · rows: A {len(a)} · B {len(b)} · C {len(c)} · D {len(cur.get('d_do_not_resume', []))}", "",
             "## A — keep, load-bearing", ""]
    lines += md_table(["asset", "path", "why it matters", "status", "verified", "next action"], [[r["title"], f"`{r['path']}`", r["why_it_matters"], r["status"], r["last_verified"], r.get("next_action", "")] for r in a])
    lines += ["", "## B — evidence / scaffolding (keep, don't lead with) — by top-level directory", ""]
    by_dir = Counter(r["path"].split("/")[0] for r in b)
    lines += md_table(["directory", "rows", "open"], [[d, str(n), "`MANIFEST.jsonl`"] for d, n in by_dir.most_common()])
    lines += ["", "## C — archive candidates (curate labels ARCHIVE-CANDIDATE / SUPERSEDED; move only through a hash-verified bag, never by deletion)", ""]
    lines += md_table(["path", "curate rule", "successor"], [[f"`{r['path']}`", r["curate_rule"], r["successor"] or "—"] for r in c])
    lines += ["", "## D — do not resume (the highest-leverage list: it is how the inventory stops repeat work)", ""]
    lines += md_table(["thing", "why it is closed", "date", "evidence"], [[d["thing"], d["why"], d["date"], f"`{d['source']}`"] for d in cur.get("d_do_not_resume", [])])
    return "\n".join(lines) + "\n"


def render_index(today: str, main: str, cur: dict, counts: dict, gate: str) -> str:
    lines = [f"<!-- GENERATED by scripts/build_sri.py on {today} at main {main[:12]}; the prose comes from CURATED.json. Keep under 150 lines. -->",
             "# Pokemon TCG agent — inventory index (L0: the map)", "",
             f"**Last inventory:** {today} · **Gate:** {gate} · **Registers:** learnings {counts['learnings']} · claims {counts['claims']} · methods {counts['methods']} · tools {counts['tools']} · decisions {counts['decisions']} · open {counts['open']} · tombstones {counts['tombstones']} · manifest {counts['manifest']}",
             "*Read this page, then open at most two registers. Depth lives in `registers/`; the sources of truth are the canonical files each row cites.*", "",
             "## What this is", cur["project_summary"], "", "## Current state", cur["current_state"], "",
             "## The five things that matter"]
    for i, f in enumerate(cur["five_things"], 1):
        lines.append(f"{i}. **{f['what']}** — `{f['path']}` — {f['why']}")
    lines += ["", "## Where to look", ""]
    lines += md_table(["I need…", "open"], [
        ["I am about to start a task (dock IN: a bounded packet with prior art, do-not-resume, open items, rules)", "`python scripts/dock.py in --task \"<what you are about to do>\"`"],
        ["I finished and have a finding to bank (dock OUT: validated, source-bound, lands in the reader's records + these registers)", "`python scripts/dock.py template > finding.json`, fill it, then `python scripts/dock.py out --finding finding.json`"],
        ["what we tried, why, what happened, what it does NOT prove", "`registers/LEARNINGS.md` (dead-ends with scope guards · instruments that lied · tried→result · graveyard · kill cards · every ledger table)"],
        ["the 2026-08 history reconstructions, canon strategy/measurement pages and index pages, row by row", "`registers/LEARNINGS.md` §History and canon surfaces (`surface:<id>` rows; `python scripts/dock.py ask \"<question>\" --kind surface:loss-modes`); coverage of the catalogued surfaces is stamped in `BUILD.json` → surface_coverage"],
        ["a number and where it can be read; whether it is retracted", "`registers/CLAIMS.md` (ids `c-nnn`; RETRACTED rows are banned)"],
        ["the sizing math, promotion rule, ladder scale, and where each is implemented", "`registers/METHODS.md`"],
        ["how to run a tool and whether it ever produced output", "`registers/TOOLS.md`"],
        ["when a tool or knowledge record entered Git and its recorded context", "`registers/TIMELINE.md` (first-add dates, not run dates; context basis depends on record kind)"],
        ["why something was chosen or killed, by date", "`registers/DECISIONS.md`"],
        ["what is still open or parked, and what would unblock it", "`registers/OPEN.md`"],
        ["which closed lines have a named reopen condition, and whether their source moved", "`registers/RETEST-QUEUE.md` (generated; nothing there is authorised)"],
        ["a question, answered with register row ids beside every hit (filter by kind or tag)", "`python scripts/dock.py ask \"<question>\" [--tag family:deck] [--kind dead-end]`"],
        ["is this document safe to publish (no retracted number or hash)?", "`python scripts/retraction_scan.py <file-or-dir>` — the firewall; a miss is not a certificate"],
        ["where a file went or what superseded it", "`registers/TOMBSTONES.md`"],
        ["every asset, value-ranked A/B/C/D with the do-not-resume list", "`INVENTORY.md`"],
        ["a machine list to diff", "`MANIFEST.jsonl`"],
        ["one experiment's original question, why, method, result, lesson, limits, reopen condition", "`registers/KNOWLEDGE-RECORDS.md` (complete, untruncated; the LEARNINGS knowledge-record rows are marked POINTERS to it) and `python scripts/research_memory.py show <E-id>` (ASTRA's reader over pinned git objects; `workflow/knowledge-register/README.md`)"],
        ["'have we already done this?'", "`python scripts/prior_art.py \"<question>\"` (searches artifacts, tools and registers)"],
        ["is this number retracted?", "`python scripts/retraction_register.py <number>`"],
        ["the task-scoped packet for the current player experiment", "`workflow/inventories/packs/player-connection.md`"],
        ["the write-up appendix generated from records", "`workflow/writeup/APPENDIX.md`"],
        ["the onboarding path, the fences, the bus", "`START-HERE.md` → `workflow/NOW.md`"],
    ])
    lines += ["", "## Do NOT resume"]
    for d in cur["d_do_not_resume"]:
        lines.append(f"- **{d['thing']}** — {d['why']} ({d['date']}, `{d['source']}`)")
    lines += ["", "## Re-run this inventory",
              "1. `python \"C:/Users/thisi/.claude/skills/curate/curate.py\" run --project <abs worktree>` (census, referrers, labels; read-only)",
              "2. `python scripts/build_sri.py` (regenerates every file here from the canonical sources) · `--check` to gate",
              "3. `python \"C:/Users/thisi/.claude/skills/inventory/scripts/validate.py\" --manifest workflow/inventories/sri/MANIFEST.jsonl --root . --claims workflow/inventories/sri/registers/CLAIMS.md`",
              "4. Answer the cold-start questions in `runs/<date>/COLD-START.md` from this page plus two registers; a question you cannot answer is a hole in the inventory.", ""]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- gate
VALIDATOR = Path.home() / ".claude" / "skills" / "inventory" / "scripts" / "validate.py"


def run_gate() -> str:
    """The SRI validator's verdict on the layer on disk, as one line for INDEX.md / BUILD.json."""
    if not VALIDATOR.exists():
        return f"validator not found on this host ({VALIDATOR}); see §Re-run"
    r = subprocess.run([sys.executable, str(VALIDATOR), "--manifest", str(OUT / "MANIFEST.jsonl"), "--root", str(REPO),
                        "--claims", str(REG / "CLAIMS.md")], capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=600)
    lines = [ln for ln in (r.stdout or "").splitlines() if ln.strip()]
    summary = next((ln for ln in lines if ln.startswith("records:")), "")
    verdict = "PASS" if r.returncode == 0 else "FAIL"
    fails = [ln.strip() for ln in lines if ln.strip().startswith("FAIL")][:3]
    return f"{verdict} — {summary}" + (" · " + " · ".join(fails) if fails else "")


# ---------------------------------------------------------------- build
def build(gate: str = "not yet run") -> dict[str, str]:
    today = date.today().isoformat()
    main = sh(["git", "rev-parse", "origin/main"]).strip() or "unknown"
    blobs = blob_map()
    cur = json.loads(CURATED.read_text(encoding="utf-8"))
    for a in cur.get("a_assets", []):
        if not (REPO / a["path"]).exists():
            raise SystemExit(f"CURATED.json names a missing A asset: {a['path']}")
    learn = harvest_learnings(blobs)
    claims = harvest_claims(blobs, today)
    qualify_claims(claims, cur, blobs)
    methods = harvest_methods(cur, blobs, today)
    tools = harvest_tools(blobs, today)
    decisions = harvest_decisions(blobs)
    opens = harvest_open(learn, blobs)
    tombs = harvest_tombstones(blobs)
    manifest = harvest_manifest(cur, blobs, today)
    timeline = harvest_timeline(tools, blobs)
    files = render_registers(today, main, learn, claims, methods, tools, decisions, opens, tombs, timeline)
    out: dict[str, str] = {f"registers/{k}": v for k, v in files.items()}
    out["MANIFEST.jsonl"] = "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in manifest)
    out["INVENTORY.md"] = render_inventory(today, main, cur, manifest)
    counts = {"learnings": len(learn), "claims": len(claims), "methods": len(methods), "tools": len(tools), "decisions": len(decisions),
              "open": len(opens), "tombstones": len(tombs), "manifest": len(manifest), "timeline": len(timeline)}
    out["INDEX.md"] = render_index(today, main, cur, counts, gate)
    # exactly one newline at EOF on every text file (CI diff hygiene: "new blank line at EOF")
    for k in list(out):
        if k.endswith(".md"):
            out[k] = out[k].rstrip("\n") + "\n"
    digest = hashlib.sha256("".join(out[k] for k in sorted(out)).encode("utf-8")).hexdigest()
    out["BUILD.json"] = json.dumps({"schema": "ptcg.sri_build/v1", "built": today, "main": main, "counts": counts, "digest": digest,
                                    "surface_coverage": surface_coverage(), "history_complete": history_is_complete(),
                                    "sources": {k: {"path": v, "blob": blobs.get(v)} for k, v in SRC.items()},
                                    "surfaces": {k: {"path": v, "blob": blobs.get(v)} for k, v in SURFACES.items()}}, indent=1) + "\n"
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--require-complete-history", action="store_true",
                    help="with --check, refuse incomplete or unverified Git history before building")
    a = ap.parse_args(argv)
    if a.require_complete_history and not a.check:
        ap.error("--require-complete-history requires --check")
    if a.require_complete_history and not history_is_complete():
        print("SRI_CHECK HISTORY UNVERIFIED: complete Git history is required; no build or comparison performed")
        return 2
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
    except (AttributeError, ValueError):
        pass
    stored_gate = "not yet run"
    if (OUT / "BUILD.json").exists():
        try:
            stored_gate = json.loads((OUT / "BUILD.json").read_text(encoding="utf-8")).get("gate", stored_gate)
        except ValueError:
            pass
    out = build(stored_gate if a.check else "not yet run")
    if a.check:
        # Two kinds of difference, and only one of them is a defect. The banner carries the build
        # DATE and the main COMMIT, both of which go stale on every merge and every midnight
        # without a single register row changing: that is staleness, not drift. A row whose text or
        # provenance blob differs IS drift — on 2026-09-06 main carried three knowledge-record rows
        # pointing at blobs that #3478 had replaced, and the old undifferentiated "advisory" line
        # hid them among stamp noise. Content drift exits 1; stamp-only staleness reports and
        # exits 0, so this check is safe to run as a gate.
        content_drift, stamp_only = [], []
        for rel, content in out.items():
            if rel == "BUILD.json":
                continue
            p = OUT / rel
            if not p.exists():
                content_drift.append(f"{rel} missing")
                continue
            on_disk = p.read_text(encoding="utf-8").replace("\r\n", "\n")
            if on_disk == content:
                continue
            (stamp_only if stamp_only_difference(rel, on_disk, content) else content_drift).append(f"{rel} differs")
        for d in stamp_only:
            print(f"SRI_CHECK STALE-STAMP (build date / main commit only, not a defect): {d}")
        if content_drift:
            for d in content_drift:
                print(f"SRI_CHECK CONTENT DRIFT: {d}")
                rel = d.removesuffix(" differs")
                if rel in out and (OUT / rel).is_file():
                    old = (OUT / rel).read_text(encoding="utf-8").splitlines()
                    new = out[rel].splitlines()
                    for i in range(max(len(old), len(new))):
                        a_line = old[i] if i < len(old) else "<EOF>"
                        b_line = new[i] if i < len(new) else "<EOF>"
                        if a_line != b_line:
                            print(f"  first difference line {i + 1}; stored: {a_line[:300]!r}; expected: {b_line[:300]!r}")
                            break
            print(f"SRI_CHECK FAIL: {len(content_drift)} file(s) differ in content — run `python scripts/build_sri.py` and commit the result")
            return 1
        print(f"SRI_CHECK OK{f' ({len(stamp_only)} file(s) stale-stamp only)' if stamp_only else ''}")
        return 0
    REG.mkdir(parents=True, exist_ok=True)
    for rel, content in out.items():
        p = OUT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")
    # Gate the layer just written and stamp the verdict into INDEX.md + BUILD.json so the map
    # says what the validator said, not "run the validator".
    gate = run_gate()
    b = json.loads(out["BUILD.json"])
    b["gate"] = gate
    (OUT / "BUILD.json").write_text(json.dumps(b, indent=1) + "\n", encoding="utf-8", newline="\n")
    cur = json.loads(CURATED.read_text(encoding="utf-8"))
    (OUT / "INDEX.md").write_text(render_index(b["built"], b["main"], cur, b["counts"], gate).rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    print(f"SRI written: {OUT.relative_to(REPO).as_posix()}/ " + " · ".join(f"{k} {v}" for k, v in b["counts"].items()) + f" · INDEX {len(out['INDEX.md'].splitlines())} lines · digest {b['digest'][:16]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
